stages:
  generate_ncol:
   cmd: bash code/bash/convert_net2ncol_all.sh
   deps:
    - code/bash/convert_net2ncol_all.sh
    - code/R/scripts/convert_net2ncol_cmd.R
    - code/R/functions/convert_net2ncol.R
    - rawdata/ctu-13/
   outs:
    - data/ncol
   metrics:
    - metrics/:
        persist: true
        cache: false
        
  calculate_bc:
   deps:
        - code/bash/calculate_bc_all.sh
        - code/R/functions/calculate_bc.R
        - code/R/scripts/calculate_bc_cmd.R
        - data/ncol/capture20110810.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110811.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110812.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110815-2.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110815-3.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110815.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110816-2.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110816-3.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110816.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110817.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110818-2.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110818.binetflow.labels-positive-weights.ncol
        - data/ncol/capture20110819.binetflow.labels-positive-weights.ncol
   cmd: bash code/bash/calculate_bc_all.sh
      
   outs:
        - data/features/bc
      
