vars:
  - base:
      netflowdir: rawdata/ctu-13/
      ncoldir: data/ncol/
  - features:
      bcdir: data/features/bc/
      dir: data/features/all/

stages:
  generate_ncol:
   cmd: bash code/bash/convert_net2ncol_all.sh  -o ${base.ncoldir} -i ${base.netflowdir}
   deps:
    - code/bash/convert_net2ncol_all.sh
    - code/R/scripts/convert_net2ncol_cmd.R
    - code/R/functions/convert_net2ncol.R
    - ${base.netflowdir}
   outs:
    - ${base.ncoldir}
   metrics:
    - metrics/:
        persist: true
        cache: false
        
  calculate_bc:
   deps:
    - code/bash/calculate_bc_all.sh
    - code/R/functions/calculate_bc.R
    - code/R/scripts/calculate_bc_cmd.R
    - ${base.ncoldir}
        
   cmd: bash code/bash/calculate_bc_all.sh -i ${base.ncoldir} -o ${features.bcdir}
      
   outs:
    - ${features.bcdir}:
        persist: true
            
  calculate_features:
   deps:
    - code/bash/calculate_features_all.sh
    - code/R/functions/calculate_features.R
    - code/R/scripts/calculate_features_cmd.R
    - ${base.ncoldir}
        
   cmd: bash code/bash/calculate_features_all.sh -i ${base.ncoldir} -o ${features.dir}
      
   outs:
    - ${features.dir}:
        persist: true
      
