vars:
  - base:
      netflowdir: rawdata/ctu-13/
      ncoldir: data/ncol/
      labelsdir: rawdata/labels/
  - features:
      bcdir: data/features/bc/
      dir: data/features/all/
      csvdir: data/features/csv/
      normdir: data/features/norm/
  - dataset:
      dir: data/labeled/
      normdir: data/labelednorm/
stages:
  generate_ncol:
   cmd: bash code/bash/convert_net2ncol_all.sh  -o ${base.ncoldir} -i ${base.netflowdir}
   deps:
    - code/bash/convert_net2ncol_all.sh
    - code/R/scripts/convert_net2ncol_cmd.R
    - code/R/functions/convert_net2ncol.R
    - ${base.netflowdir}
   outs:
    - ${base.ncoldir}
   metrics:
    - metrics/:
        persist: true
        cache: false
        
  calculate_bc:
   deps:
    - code/bash/calculate_bc_all.sh
    - code/R/functions/calculate_bc.R
    - code/R/scripts/calculate_bc_cmd.R
    - ${base.ncoldir}
        
   cmd: bash code/bash/calculate_bc_all.sh -i ${base.ncoldir} -o ${features.bcdir}
      
   outs:
    - ${features.bcdir}:
        persist: true
            
  calculate_features:
   deps:
    - code/bash/calculate_features_all.sh
    - code/R/functions/calculate_features.R
    - code/R/scripts/calculate_features_cmd.R
    - ${base.ncoldir}
        
   cmd: bash code/bash/calculate_features_all.sh -i ${base.ncoldir} -o ${features.dir}
      
   outs:
    - ${features.dir}:
        persist: true
  merge_features:
    deps:
    - code/bash/merge_features_all.sh
    - code/R/scripts/merge_features_cmd.R
    - ${features.bcdir}
    - ${features.dir}
    
    cmd: bash code/bash/merge_features_all.sh -f ${features.dir} -b ${features.bcdir} -o ${features.csvdir}
   
    outs:
    - ${features.csvdir}:
        persist: true
  
  normalize_features:
    deps:
    - code/bash/normalize_features_all.sh
    - code/R/scripts/normalize_features_cmd.R
    - code/R/functions/normalize_feature.R
    - ${features.csvdir}
    - ${base.ncoldir}
    
    cmd: bash code/bash/normalize_features_all.sh -n ${base.ncoldir} -f ${features.csvdir} -o ${features.normdir}
    
    outs:
    - ${features.normdir}:
        persist: true
    
     
  label_dataset:
    deps:
    - code/bash/label_dataset_all.sh
    - code/R/scripts/label_dataset_cmd.R
    - code/R/functions/label_dataset.R
    - ${features.csvdir}
    - ${base.labelsdir}
    
    cmd: bash code/bash/label_dataset_all.sh -i ${features.csvdir} -l ${base.labelsdir} -o ${dataset.dir}
   
    outs:
    - ${dataset.dir}:
        persist: true
        
  label_dataset_normalized:
    deps:
    - code/bash/label_dataset_all.sh
    - code/R/scripts/label_dataset_cmd.R
    - code/R/functions/label_dataset.R
    - ${features.normdir}
    - ${base.labelsdir}
    
    cmd: bash code/bash/label_dataset_all.sh -i ${features.normdir} -l ${base.labelsdir} -o ${dataset.normdir}
   
    outs:
    - ${dataset.normdir}:
        persist: true
    
      
