calculate_ac:
  alphas: 
   - -0.1
   - -0.01
   - 0.001
   - 0.01
   - 0.05
   - 0.1
   - 0.2
   - 0.4
   - 0.6
   - 0.8

tune_best_ac_for_kmeans:
  centroids:
    - 4
    - 9   
    - 16
    - 25
    - 36  
    - 49  
    - 64  
    - 81  
    - 100  
    - 121 
    - 144 
    - 169 
    - 196
    - 225 
