---
title: "Convert netflow data to graph"
output: html_notebook
---


# Checking bidireccionality on netflow file
```{r}
library(readr)
library(dplyr)
ctu_netflow<-
  read_csv("../../rawdata/ctu-13/capture20110810.binetflow.labels.gz")

ctu_netflow <- 
  ctu_netflow %>% 
  filter(Proto %in% c("udp", "tcp")) %>% 
  mutate(DstBytes = TotBytes-SrcBytes) %>%
    select(SrcAddr, DstAddr, DstBytes, SrcBytes) 

# create src_dst and dst_src keys
ctu_netflow_srcdst <- ctu_netflow %>% 
  select(SrcAddr, DstAddr, SrcBytes, DstBytes) %>% 
  tidyr::unite("src_dst", c("SrcAddr","DstAddr")) 
ctu_netflow_dstsrc<-ctu_netflow %>% 
  select(SrcAddr,DstAddr, SrcBytes, DstBytes) %>% 
  tidyr::unite("dst_src", c("DstAddr","SrcAddr")) 

# aggregate Bytes from src_dst and dst_src
ctu_netflow_src_dst_agg <- ctu_netflow_srcdst %>% 
  group_by(src_dst) %>% 
  summarise(TotSrcBytes = sum(SrcBytes),
            TotDstBytes = sum(DstBytes))
ctu_netflow_dst_src_agg <- ctu_netflow_dstsrc %>% 
  group_by(dst_src) %>% 
  summarise(TotSrcBytes = sum(SrcBytes),
            TotDstBytes = sum(DstBytes))

ctu_netflow_4tuple<-left_join(ctu_netflow_src_dst_agg,
                               ctu_netflow_dst_src_agg,
                               by=c("src_dst"="dst_src")) %>%
  mutate_all(~replace(., is.na(.), 0))

ctu_netflow_4tuple <-
  ctu_netflow_4tuple %>% mutate(TotSrcBytes = TotSrcBytes.x + TotDstBytes.y,
                                TotDstBytes = TotDstBytes.x + TotSrcBytes.y) %>%
  select(src_dst, TotSrcBytes, TotDstBytes) 

unique_ctu_netflow_4tuple <- 
  ctu_netflow_4tuple %>%  
  tidyr::separate(src_dst, c("SrcAddr", "DstAddr"), sep = "_") %>% #select(SrcAddr, DstAddr) %>%
  group_by(grp = paste(pmax(SrcAddr, DstAddr), pmin(SrcAddr, DstAddr), sep = "_")) %>%
  slice(1) %>%
  ungroup() %>%
  select(-grp) %>% tidyr::unite("src_dst", c("SrcAddr", "DstAddr"))


#unique_ctu_netflow_4tuple %>% filter(src_dst=="111.221.102.89_147.32.84.1")
#ctu_netflow_4tuple %>% filter(src_dst=="111.221.102.89_147.32.84.1")
#left_join(unique_ctu_netflow_4tuple,ctu_netflow_4tuple,by="src_dst")

#ctu_netflow_4tuple %>% select(everything()) %>%  # replace to your needs
#  summarise_all(funs(sum(is.na(.))))


```

## Convert netflow to dot
```{r message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(igraph)

ctu_netflow<-read_csv("../../rawdata/ctu-13/capture20110810.binetflow.labels.gz")
ctu_netflow_filtered<-ctu_netflow %>% filter(Proto %in% c("udp","tcp")) %>% select(SrcAddr,DstAddr,TotPkts) %>% tidyr::unite("src_dst",c("SrcAddr","DstAddr"))

ctu_netflow_src_dst_agg <- ctu_netflow_filtered %>% group_by(src_dst) %>% summarise(TotPkts=sum(TotPkts))
ctu_netflow_agg<-ctu_netflow_src_dst_agg %>% tidyr::separate(src_dst,c("src","dst"),sep="_")

## igraph
#nodes <- c(ctu_netflow_agg$src ,ctu_netflow_agg$dst) %>% unique()
links <- ctu_netflow_agg %>% select(src,dst,TotPkts) %>% unique()
net <- graph_from_data_frame(d=links, directed = T ) 
## Weights
E(net)$weight <-links %>% select(TotPkts)  %>% unname() %>% unlist()
```

# Calculate degree and weight degree
```{r}
graph_degree_in<-degree(net,V(net),mode = "in")
graphs_trength_in<-strength(net,V(net),mode = "in")
graphs_trength_out<-strength(net,V(net),mode = "out")
graphs_trength_out %>% order() %>% head()
```





## calculate BC
```{r}
library(doMC)
registerDoMC(8)
#bc<-betweenness(net, e = E(net), directed = TRUE)
start<-Sys.time()
bc<-estimate_betweenness(
  net,
  v = V(net),
  directed = TRUE,
  weights = NULL,
  cutoff = 2,
#  normalized = FALSE
)
stop<-Sys.time()
stop-start
```



## Plot (do not use for big graphs)
```{r fig.height=12, fig.width=12}
plot(net, edge.arrow.size=.1,
     vertex.label=NA,
     vertex.size=1,
     edge.curved=.1)
```

