---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
rm(list = ls()) # clean global environment
cat("\014")  # clean the console
```



```{r setup, warning=FALSE}
# CHANGE TO THE CORRESPONDING WORKING DIRECTORY
knitr::opts_knit$set(root.dir = '/home/harpo/Dropbox/ongoing-work/git-repos/graph-representation-learning/')
```

```{r message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
```
# Read dataset
```{r}
features_data<-rbind(
  readr::read_csv("data/labeled/capture20110810.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110811.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110812.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110815.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110815-2.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110815-3.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110816.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110816-2.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110816-3.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110818.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110818-2.binetflow.labels-positive-weights.labeled.csv"),
  readr::read_csv("data/labeled/capture20110819.binetflow.labels-positive-weights.labeled.csv")
)
features_data

```
# Read F-norm dataset

```{r}
features_norm_data<-rbind(
  readr::read_csv("data/labelednorm/capture20110810.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110811.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110812.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110815.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110815-2.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110815-3.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110816.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110816-2.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110816-3.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110818.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110818-2.binetflow.labels-positive-weights.ncol.normalized.labeled.csv"),
  readr::read_csv("data/labelednorm/capture20110819.binetflow.labels-positive-weights.ncol.normalized.labeled.csv")
)
features_norm_data

```

# Select Features
```{r}
#selected_features <- c("ID","OD","IDW","ODW","BC")
selected_features <- c("ID","OD","IDW","ODW","BC","LCC")
#selected_features <- c("AC")

features_norm_data_2 <- features_norm_data %>% mutate(across(is.numeric,function(x) log(x+10000)))
```

```{r}
features_data %>% group_by(label) %>% count()
features_data  %>% filter (ID != 0 & ID !=1) %>% filter(ID >=3 ) %>% arrange(desc(ID) )

```
# Boxplots
## Features
```{r fig.height=10, fig.width=12}
p_features<-features_data %>% select(any_of(selected_features),"label" ) %>%  reshape2::melt() %>%
  ggplot()+
  facet_wrap(~variable,scales = "free_y")+
  geom_boxplot(aes(y=value,x=label,color=label))+
  labs(title="Features")+
  ylim(-1000,1000)+
  theme_classic()
p_features
#plotly::ggplotly()
```



## Normalized Features

```{r fig.height=10, fig.width=12}
p_features_norm<-features_norm_data %>% select(any_of(selected_features),"label" ) %>% reshape2::melt() %>%
  ggplot()+
  facet_wrap(~variable,scales = "free_y")+
  geom_boxplot(aes(y=value,x=label,color=label))+
  #ylim(0,1000)+
  labs(title="Normalized  Features")+
  theme_classic()
p_features_norm
```

# Clustering
```{r}
cluster_data <- kmeans(features_data %>% select(any_of(selected_features)),centers = 100,nstart = 10, iter.max = 1000)
features_norm_cluster<-data.frame(features_norm_data,cluster=cluster_data$cluster)
gc()
```

```{r}
clusters_size <- features_norm_cluster %>% group_by(cluster) %>% count()
clusters_size %>% arrange(desc(n))
begnin_cluster<-clusters_size  %>% arrange(desc(n)) %>% head(1) %>% select(cluster) %>% unlist() %>% unname()
features_norm_cluster %>% filter(cluster == begnin_cluster) %>% group_by(label) %>% count()
```

## PCA
```{r eval=FALSE, include=FALSE}
pca_data <- prcomp(features_norm_data %>% select(any_of(selected_features)), center = TRUE, scale. = FALSE)
```

```{r eval=FALSE, include=FALSE}
features_norm_pca_cluster<-data.frame(pca_data$x,
                                      cluster=cluster_data$cluster,
                                      label=features_norm_data$label)
features_norm_pca_cluster
```



## Visualize PCA + Clustering
```{r }
features_norm_pca_cluster |> sample_frac(0.01) %>%
  ggplot()+
  geom_jitter(aes(x=PC1,y=PC2,color=as.factor(cluster)),size=2,alpha=0.2)+
  theme_classic()+
  ylim(c(0,150))+
  theme(legend.position = "")
plotly::ggplotly()
```

