---
title: "Convert netflow data to graph"
output: html_notebook
---
```{r}
source("convert_net2graph.R")

net_csv<-read_csv("../../test.csv")
net_csv %>% filter(weights == 0)
```


# Checking bidireccionality on netflow file
```{r}
library(readr)
library(dplyr)
ctu_netflow<-
  read_csv("../../rawdata/ctu-13/capture20110810.binetflow.labels.gz")

ctu_netflow <- 
  ctu_netflow %>% 
  filter(Proto %in% c("udp", "tcp")) %>% 
  mutate(DstBytes = TotBytes-SrcBytes) %>%
    select(SrcAddr, DstAddr, DstBytes, SrcBytes) 

# create src_dst and dst_src keys
ctu_netflow_srcdst <- ctu_netflow %>% 
  select(SrcAddr, DstAddr, SrcBytes, DstBytes) %>% 
  tidyr::unite("src_dst", c("SrcAddr","DstAddr")) 
ctu_netflow_dstsrc<-ctu_netflow %>% 
  select(SrcAddr,DstAddr, SrcBytes, DstBytes) %>% 
  tidyr::unite("dst_src", c("DstAddr","SrcAddr")) 

# aggregate Bytes from src_dst and dst_src
ctu_netflow_src_dst_agg <- ctu_netflow_srcdst %>% 
  group_by(src_dst) %>% 
  summarise(TotSrcBytes = sum(SrcBytes),
            TotDstBytes = sum(DstBytes))
ctu_netflow_dst_src_agg <- ctu_netflow_dstsrc %>% 
  group_by(dst_src) %>% 
  summarise(TotSrcBytes = sum(SrcBytes),
            TotDstBytes = sum(DstBytes))

ctu_netflow_4tuple<-left_join(ctu_netflow_src_dst_agg,
                               ctu_netflow_dst_src_agg,
                               by=c("src_dst"="dst_src")) %>%
  mutate_all(~replace(., is.na(.), 0))

ctu_netflow_4tuple <-
  ctu_netflow_4tuple %>% mutate(TotSrcBytes = TotSrcBytes.x + TotDstBytes.y,
                                TotDstBytes = TotDstBytes.x + TotSrcBytes.y) %>%
  select(src_dst, TotSrcBytes, TotDstBytes) 

unique_ctu_netflow_4tuple <- 
  ctu_netflow_4tuple %>%  
  tidyr::separate(src_dst, c("SrcAddr", "DstAddr"), sep = "_") %>% #select(SrcAddr, DstAddr) %>%
  group_by(grp = paste(pmax(SrcAddr, DstAddr), pmin(SrcAddr, DstAddr), sep = "_")) %>%
  slice(1) %>%
  ungroup() %>%
  select(-grp) %>% tidyr::unite("src_dst", c("SrcAddr", "DstAddr"))


 links <-
    unique_ctu_netflow_4tuple %>%  
    tidyr::separate(src_dst, c("SrcAddr", "DstAddr"), sep = "_") %>%
    select(SrcAddr, DstAddr, TotSrcBytes, TotDstBytes) 
  
  net <-
    graph_from_data_frame(d = links,directed = T)
  E(net)$weight <-
    links %>% select(TotPkts)  %>% unname() %>% unlist()
  net

#unique_ctu_netflow_4tuple %>% filter(src_dst=="111.221.102.89_147.32.84.1")
#ctu_netflow_4tuple %>% filter(src_dst=="111.221.102.89_147.32.84.1")
#left_join(unique_ctu_netflow_4tuple,ctu_netflow_4tuple,by="src_dst")

#ctu_netflow_4tuple %>% select(everything()) %>%  # replace to your needs
#  summarise_all(funs(sum(is.na(.))))


```
## Tati's approach
```{r}
ctu_netflow<-
  read_csv("../../rawdata/ctu-13/capture20110810.binetflow.labels.gz")

ctu_netflow <- 
  ctu_netflow %>% 
  filter(Proto %in% c("udp", "tcp")) %>% 
  mutate(DstBytes = TotBytes-SrcBytes) %>%
    select(SrcAddr, DstAddr, DstBytes, SrcBytes) 

ctu_netflow %>% filter(SrcBytes==0)
# create src_dst and dst_src keys
ctu_netflow_srcdst <- ctu_netflow %>% 
  select(SrcAddr, DstAddr, SrcBytes) %>% rename(origin=SrcAddr,destination="DstAddr",weight="SrcBytes")
 
ctu_netflow_dstsrc<-ctu_netflow %>% 
  select(DstAddr, SrcAddr, DstBytes) %>% rename(origin=DstAddr,destination="SrcAddr",weight="DstBytes")
  

ctu_netflow_all<-rbind(ctu_netflow_dstsrc,ctu_netflow_srcdst) 
ctu_netflow_all<- ctu_netflow_all %>% group_by(origin,destination) %>% summarise(weight=sum(weight)) %>% ungroup()

links <- ctu_netflow_all %>% select(origin,destination,weight)
net <- graph_from_data_frame(d=links, directed = T ) 
## Weights
E(net)$weight <-links %>% select(weight)  %>% unname() %>% unlist()

#write_graph(net,file="/tmp/caca.ncol",format="ncol")
#ctu_netflow_all %>% ungroup() %>% filter(origin=="147.32.84.10" & destination=="147.32.80.9")
#read_graph()

links %>% filter(weight == 0)
```

## Convert netflow to dot
```{r message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(igraph)

ctu_netflow<-read_csv("../../rawdata/ctu-13/capture20110810.binetflow.labels.gz")
ctu_netflow_filtered<-ctu_netflow %>% filter(Proto %in% c("udp","tcp")) %>% select(SrcAddr,DstAddr,TotPkts) %>% tidyr::unite("src_dst",c("SrcAddr","DstAddr"))

ctu_netflow_src_dst_agg <- ctu_netflow_filtered %>% group_by(src_dst) %>% summarise(TotPkts=sum(TotPkts))
ctu_netflow_agg<-ctu_netflow_src_dst_agg %>% tidyr::separate(src_dst,c("src","dst"),sep="_")

## igraph
#nodes <- c(ctu_netflow_agg$src ,ctu_netflow_agg$dst) %>% unique()
links <- ctu_netflow_agg %>% select(src,dst,TotPkts) %>% unique()
net <- graph_from_data_frame(d=links, directed = T ) 
## Weights
E(net)$weight <-links %>% select(TotPkts)  %>% unname() %>% unlist()
```

# Calculate degree and weight degree
```{r}
graph_degree_in<-degree(net,V(net),mode = "in")
graph_degree_out<-strength(net,V(net),mode = "out")
graphs_trength_out<-strength(net,V(net),mode = "out")
graphs_trength_out %>% order() %>% head()

df1<-graph_degree_in %>% as.data.frame()
df2<-graph_degree_out %>% as.data.frame()
df2
V(net) %>% as.list()
graphs_trength_in %>% unname()
```





## calculate BC
```{r}
library(doMC)

registerDoMC(8)
#bc<-betweenness(net, e = E(net), directed = TRUE)
start<-Sys.time()
bc<-estimate_betweenness(
  net,
  v = V(net),
  directed = TRUE,
  weights = NULL,
  cutoff = 2,
#  normalized = FALSE
)
stop<-Sys.time()
stop-start
```



## Plot (do not use for big graphs)
```{r fig.height=12, fig.width=12}
library(readr)
library(dplyr)
net_df <- read_delim("../../../test-mini-2.ncol", delim= " ", col_names = F)
net_df <- net_df %>% filter(X3 == 0)

net_df <- net_df %>% sample_frac(0.1)

net <- igraph::graph_from_data_frame(d=net_df, directed = T)
 layout = layout.drl
  V(net)$size = degree(net) /max(degree(net))
  graph_plot<-plot(net, 
       edge.arrow.size=0.01,
       edge.width= 0.01,
       #edge.width=E(net)$weight,
       vertex.label=NA,
       edge.curved=1, 
        layout = layout,
    # layout=layout.fruchterman.reingold,
      # asp =9/16
       )
```

```{r}
library(igraph)
  net<-read_graph("../../../test-mini-2.ncol", format='ncol')
  
  
  delete_edges(net, which(E(net)$weight==0))
  
  source("../functions/calculate_bc.R")
  
  bc<-calculate_bc(net)
  #save(bc,file="bc.rdata")
  
  #load("bc.rdata")
bc %>% as.data.frame() %>% tibble::rownames_to_column("node")
```


```{r}
library(parallel)
computeLocalClusteringCoefficient <- function(graph, vertex) {
    # Calculate LCC for a vertex in graph
   
    neighbourhood <- ego(graph, order = 1, nodes = vertex, mode = "all", mindist = 1) 
    k <- ego_size(graph, order = 1, nodes = vertex, mode = "all", mindist = 1) 
    # https://igraph.org/r/doc/ego.html
    # see (1)
    numberTriplets <- 0
    neighbourhood<-as.vector(neighbourhood[[1]])
    for (p in neighbourhood) {
        for (q in neighbourhood) {
            if (igraph::are_adjacent(graph, p, q)) {
                # https://igraph.org/r/doc/are_adjacent.html
                # see (2)
                numberTriplets <- numberTriplets + 1
            }
        }
    }
    print(numberTriplets)
    if (k <= 1) {
        return(0.0)
    } else {
        return(numberTriplets / (k * (k - 1)))
    }
}
```

```{r}
net<-read_graph("../../../data/ncol/capture20110815-2.binetflow.labels-positive-weights.ncol", 
                
                format='ncol', directed = TRUE)
##### Calculate Local Clustering Coefficient (LCC) #####
LCC <- mclapply(V(net), function(x) computeLocalClusteringCoefficient(net,x),mc.cores = 10)
lcc<-computeLocalClusteringCoefficient(net,V(net)[4])
lcc
```

```{r}
library(parallel)
computeLocalClusteringCoefficient <- function(graph, vertex) {
    # Calculate LCC for a vertex in graph
   
    neighbourhood <- ego(graph, order = 1, nodes = vertex, mode = "all", mindist = 1) 
    k <- ego_size(graph, order = 1, nodes = vertex, mode = "all", mindist = 1) 
    # https://igraph.org/r/doc/ego.html
    # see (1)
    numberTriplets <- 0
    neighbourhood<-as.vector(neighbourhood[[1]])
    for (p in neighbourhood) {
        for (q in neighbourhood) {
            if (igraph::are_adjacent(graph, p, q)) {
                # https://igraph.org/r/doc/are_adjacent.html
                # see (2)
                numberTriplets <- numberTriplets + 1
            }
        }
    }
    print(numberTriplets)
    if (k <= 1) {
        return(0.0)
    } else {
        return(numberTriplets / (k * (k - 1)))
    }
}
net <- make_full_graph(4000)
lcc<-computeLocalClusteringCoefficient(net,V(net)[1])

vertex <- V(net)[1]
neighbourhood <-
  ego(
    net,
    order = 1,
    nodes = vertex,
    mode = "all",
    mindist = 1
  )
neighbourhood <- neighbourhood[[1]]
k <-
  ego_size(
    net,
    order = 1,
    nodes = vertex,
    mode = "all",
    mindist = 1
  )
k
d <- mclapply(neighbourhood,
              function(p) {
                purrr::map2(neighbourhood, p,
                            function(q, p) {
                              if (igraph::are_adjacent(net, p, q)) {
                                1
                              }
                            })
              }
              , mc.cores = 10)
numberTriplets <- d %>% unlist() %>% sum()
print(numberTriplets)

 if (k <= 1){
        lcc2<-0
 } else{ 
    lcc2<-(numberTriplets / (k * (k - 1)))
  }
lcc
lcc2
```



```{r}
library(igraph)
source("../functions/calculate_features.R")
    
net<-read_graph("../../../data/ncol/capture20110815-2.binetflow.labels-positive-weights.ncol", format='ncol', directed = TRUE)
igraph::is.weighted(net)
net <- igraph::as.directed(net)
net_un<-igraph::as.undirected(net, mode = "collapse")

lcc <-igraph::transitivity(net_un,
                         type = "local",
                         isolates = "zero" ,
                         weights = NULL)
  lcc<-calculate_lcc(net_un)
  features<-calculate_degree(net)
  
  lcc %>% as.data.frame()
  lcc %>% as.data.frame() %>% rownames_to_column()
  #save(bc,file="bc.rdata")
  
which(lcc != 0)  
  #load("bc.rdata")
bc %>% as.data.frame() %>% tibble::rownames_to_column("node")

igraph::is_directed(net_un)
igraph::is_directed(net)
igraph::read.graph()
```


```{r}
library(dplyr)
features<- readr::read_csv("../../../data/features/all/capture20110810.binetflow.labels-positive-weights.features")
bc_feature <- readr::read_csv("../../../data/features/bc/capture20110810.binetflow.labels-positive-weights.bc")
names(bc_feature)<-c("node","BC")
features_f<-cbind(bc_feature,features)
labels <- readr::read_csv("../../../rawdata/labels/capture20110810.nodes.labels",col_names = F)
nodes_infected <- labels %>% dplyr::filter(X3 == "infected") %>% select(X1) %>% unname() %>% unlist()

features_f$label<-"normal"
features_f %>% group_by(node) %>% count()
dataset<-features_f %>% mutate(label=ifelse(node %in% nodes_infected, "infected", "normal"))
dataset %>% filter(node == "147.32.84.165")
```

```{r}
normalizeFeature <- function(featureTarget, neighbourhood, k, index) {
    numberNeighbours <- k[index]
    localNeighbourhood <- neighbourhood[index][[1]]
    suma <- 0
    for(i in localNeighbourhood) {
        suma <- suma + featureTarget[i, 2]
    }
    
    if(suma != 0) {
        mu <- suma / numberNeighbours
        return(as.numeric(featureTarget[index,2]/mu))
    } else {
        return(as.numeric(featureTarget[index,2]))
    }
}
```

```{r}
library(igraph)
library(dplyr)
net<-read_graph("../../../data/ncol/capture20110815-2.binetflow.labels-positive-weights.ncol", format='ncol',directed = TRUE)
neighbourhood <- ego(net, order = 1, nodes = V(net), mode = "all", mindist = 1) 
names(neighbourhood) <- V(net)$name
k<-purrr::map(neighbourhood, function(x) length(x))
features <- readr::read_csv("../../../data/features/csv/capture20110815-2.binetflow.labels-positive-weights.csv")
features_names<-colnames(features)[2:ncol(features)]
res <- list()
for(feature in features_names){
  featuretarget <- features |> select(node,feature)
   res[[feature]] <- sapply(seq(1,length(V(net))), function(x) normalizeFeature(featureTarget = featuretarget,neighbourhood,k,x ))
}


res %>% as.data.frame() %>% tibble::add_column(node=features$node) %>% select(names(features))
```



```{r}
library(reticulate)
```

```{python}
import networkx as nx
nx_graph = nx.read_weighted_edgelist(path="/home/harpo/Dropbox/ongoing-work/git-repos/graph-representation-learning/data/ncol/capture20110810.binetflow.labels.ncol")
nx_graph.edges
```

```{r}
list("a" = runif(100), "b" = runif(100)) %>% as.data.frame()
```

